// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: VisualObj.proto

package com.github.phantomv1989.diabrox.data;

public final class VisualObj {
  private VisualObj() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface VisualNodeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.github.phantomv1989.diabrox.data.VisualNode)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string name = 1;</code>
     */
    boolean hasName();
    /**
     * <code>required string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>required string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>required int32 id = 2;</code>
     */
    boolean hasId();
    /**
     * <code>required int32 id = 2;</code>
     */
    int getId();

    /**
     * <code>required int32 value = 3;</code>
     */
    boolean hasValue();
    /**
     * <code>required int32 value = 3;</code>
     */
    int getValue();

    /**
     * <code>required int32 type = 4;</code>
     */
    boolean hasType();
    /**
     * <code>required int32 type = 4;</code>
     */
    int getType();

    /**
     * <code>repeated .com.github.phantomv1989.diabrox.data.VisualNode children = 5;</code>
     */
    java.util.List<com.github.phantomv1989.diabrox.data.VisualObj.VisualNode> 
        getChildrenList();
    /**
     * <code>repeated .com.github.phantomv1989.diabrox.data.VisualNode children = 5;</code>
     */
    com.github.phantomv1989.diabrox.data.VisualObj.VisualNode getChildren(int index);
    /**
     * <code>repeated .com.github.phantomv1989.diabrox.data.VisualNode children = 5;</code>
     */
    int getChildrenCount();
    /**
     * <code>repeated .com.github.phantomv1989.diabrox.data.VisualNode children = 5;</code>
     */
    java.util.List<? extends com.github.phantomv1989.diabrox.data.VisualObj.VisualNodeOrBuilder> 
        getChildrenOrBuilderList();
    /**
     * <code>repeated .com.github.phantomv1989.diabrox.data.VisualNode children = 5;</code>
     */
    com.github.phantomv1989.diabrox.data.VisualObj.VisualNodeOrBuilder getChildrenOrBuilder(
        int index);
  }
  /**
   * <pre>
   * [START messages]
   * </pre>
   *
   * Protobuf type {@code com.github.phantomv1989.diabrox.data.VisualNode}
   */
  public  static final class VisualNode extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.github.phantomv1989.diabrox.data.VisualNode)
      VisualNodeOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use VisualNode.newBuilder() to construct.
    private VisualNode(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private VisualNode() {
      name_ = "";
      id_ = 0;
      value_ = 0;
      type_ = 0;
      children_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private VisualNode(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              name_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              id_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              value_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              type_ = input.readInt32();
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                children_ = new java.util.ArrayList<com.github.phantomv1989.diabrox.data.VisualObj.VisualNode>();
                mutable_bitField0_ |= 0x00000010;
              }
              children_.add(
                  input.readMessage(com.github.phantomv1989.diabrox.data.VisualObj.VisualNode.PARSER, extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          children_ = java.util.Collections.unmodifiableList(children_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.phantomv1989.diabrox.data.VisualObj.internal_static_com_github_phantomv1989_diabrox_data_VisualNode_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.phantomv1989.diabrox.data.VisualObj.internal_static_com_github_phantomv1989_diabrox_data_VisualNode_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.phantomv1989.diabrox.data.VisualObj.VisualNode.class, com.github.phantomv1989.diabrox.data.VisualObj.VisualNode.Builder.class);
    }

    private int bitField0_;
    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>required string name = 1;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ID_FIELD_NUMBER = 2;
    private int id_;
    /**
     * <code>required int32 id = 2;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 id = 2;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int VALUE_FIELD_NUMBER = 3;
    private int value_;
    /**
     * <code>required int32 value = 3;</code>
     */
    public boolean hasValue() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 value = 3;</code>
     */
    public int getValue() {
      return value_;
    }

    public static final int TYPE_FIELD_NUMBER = 4;
    private int type_;
    /**
     * <code>required int32 type = 4;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int32 type = 4;</code>
     */
    public int getType() {
      return type_;
    }

    public static final int CHILDREN_FIELD_NUMBER = 5;
    private java.util.List<com.github.phantomv1989.diabrox.data.VisualObj.VisualNode> children_;
    /**
     * <code>repeated .com.github.phantomv1989.diabrox.data.VisualNode children = 5;</code>
     */
    public java.util.List<com.github.phantomv1989.diabrox.data.VisualObj.VisualNode> getChildrenList() {
      return children_;
    }
    /**
     * <code>repeated .com.github.phantomv1989.diabrox.data.VisualNode children = 5;</code>
     */
    public java.util.List<? extends com.github.phantomv1989.diabrox.data.VisualObj.VisualNodeOrBuilder> 
        getChildrenOrBuilderList() {
      return children_;
    }
    /**
     * <code>repeated .com.github.phantomv1989.diabrox.data.VisualNode children = 5;</code>
     */
    public int getChildrenCount() {
      return children_.size();
    }
    /**
     * <code>repeated .com.github.phantomv1989.diabrox.data.VisualNode children = 5;</code>
     */
    public com.github.phantomv1989.diabrox.data.VisualObj.VisualNode getChildren(int index) {
      return children_.get(index);
    }
    /**
     * <code>repeated .com.github.phantomv1989.diabrox.data.VisualNode children = 5;</code>
     */
    public com.github.phantomv1989.diabrox.data.VisualObj.VisualNodeOrBuilder getChildrenOrBuilder(
        int index) {
      return children_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasValue()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getChildrenCount(); i++) {
        if (!getChildren(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, id_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, value_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, type_);
      }
      for (int i = 0; i < children_.size(); i++) {
        output.writeMessage(5, children_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, id_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, value_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, type_);
      }
      for (int i = 0; i < children_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, children_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.github.phantomv1989.diabrox.data.VisualObj.VisualNode)) {
        return super.equals(obj);
      }
      com.github.phantomv1989.diabrox.data.VisualObj.VisualNode other = (com.github.phantomv1989.diabrox.data.VisualObj.VisualNode) obj;

      boolean result = true;
      result = result && (hasName() == other.hasName());
      if (hasName()) {
        result = result && getName()
            .equals(other.getName());
      }
      result = result && (hasId() == other.hasId());
      if (hasId()) {
        result = result && (getId()
            == other.getId());
      }
      result = result && (hasValue() == other.hasValue());
      if (hasValue()) {
        result = result && (getValue()
            == other.getValue());
      }
      result = result && (hasType() == other.hasType());
      if (hasType()) {
        result = result && (getType()
            == other.getType());
      }
      result = result && getChildrenList()
          .equals(other.getChildrenList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasName()) {
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
      }
      if (hasId()) {
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + getId();
      }
      if (hasValue()) {
        hash = (37 * hash) + VALUE_FIELD_NUMBER;
        hash = (53 * hash) + getValue();
      }
      if (hasType()) {
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + getType();
      }
      if (getChildrenCount() > 0) {
        hash = (37 * hash) + CHILDREN_FIELD_NUMBER;
        hash = (53 * hash) + getChildrenList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.github.phantomv1989.diabrox.data.VisualObj.VisualNode parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.phantomv1989.diabrox.data.VisualObj.VisualNode parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.phantomv1989.diabrox.data.VisualObj.VisualNode parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.phantomv1989.diabrox.data.VisualObj.VisualNode parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.phantomv1989.diabrox.data.VisualObj.VisualNode parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.phantomv1989.diabrox.data.VisualObj.VisualNode parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.phantomv1989.diabrox.data.VisualObj.VisualNode parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.phantomv1989.diabrox.data.VisualObj.VisualNode parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.phantomv1989.diabrox.data.VisualObj.VisualNode parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.github.phantomv1989.diabrox.data.VisualObj.VisualNode parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.phantomv1989.diabrox.data.VisualObj.VisualNode parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.phantomv1989.diabrox.data.VisualObj.VisualNode parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.github.phantomv1989.diabrox.data.VisualObj.VisualNode prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * [START messages]
     * </pre>
     *
     * Protobuf type {@code com.github.phantomv1989.diabrox.data.VisualNode}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.github.phantomv1989.diabrox.data.VisualNode)
        com.github.phantomv1989.diabrox.data.VisualObj.VisualNodeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.phantomv1989.diabrox.data.VisualObj.internal_static_com_github_phantomv1989_diabrox_data_VisualNode_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.phantomv1989.diabrox.data.VisualObj.internal_static_com_github_phantomv1989_diabrox_data_VisualNode_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.phantomv1989.diabrox.data.VisualObj.VisualNode.class, com.github.phantomv1989.diabrox.data.VisualObj.VisualNode.Builder.class);
      }

      // Construct using com.github.phantomv1989.diabrox.data.VisualObj.VisualNode.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getChildrenFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        value_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        type_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        if (childrenBuilder_ == null) {
          children_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
        } else {
          childrenBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.phantomv1989.diabrox.data.VisualObj.internal_static_com_github_phantomv1989_diabrox_data_VisualNode_descriptor;
      }

      @java.lang.Override
      public com.github.phantomv1989.diabrox.data.VisualObj.VisualNode getDefaultInstanceForType() {
        return com.github.phantomv1989.diabrox.data.VisualObj.VisualNode.getDefaultInstance();
      }

      @java.lang.Override
      public com.github.phantomv1989.diabrox.data.VisualObj.VisualNode build() {
        com.github.phantomv1989.diabrox.data.VisualObj.VisualNode result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.github.phantomv1989.diabrox.data.VisualObj.VisualNode buildPartial() {
        com.github.phantomv1989.diabrox.data.VisualObj.VisualNode result = new com.github.phantomv1989.diabrox.data.VisualObj.VisualNode(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.value_ = value_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.type_ = type_;
        if (childrenBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010)) {
            children_ = java.util.Collections.unmodifiableList(children_);
            bitField0_ = (bitField0_ & ~0x00000010);
          }
          result.children_ = children_;
        } else {
          result.children_ = childrenBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.phantomv1989.diabrox.data.VisualObj.VisualNode) {
          return mergeFrom((com.github.phantomv1989.diabrox.data.VisualObj.VisualNode)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.phantomv1989.diabrox.data.VisualObj.VisualNode other) {
        if (other == com.github.phantomv1989.diabrox.data.VisualObj.VisualNode.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasValue()) {
          setValue(other.getValue());
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        if (childrenBuilder_ == null) {
          if (!other.children_.isEmpty()) {
            if (children_.isEmpty()) {
              children_ = other.children_;
              bitField0_ = (bitField0_ & ~0x00000010);
            } else {
              ensureChildrenIsMutable();
              children_.addAll(other.children_);
            }
            onChanged();
          }
        } else {
          if (!other.children_.isEmpty()) {
            if (childrenBuilder_.isEmpty()) {
              childrenBuilder_.dispose();
              childrenBuilder_ = null;
              children_ = other.children_;
              bitField0_ = (bitField0_ & ~0x00000010);
              childrenBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getChildrenFieldBuilder() : null;
            } else {
              childrenBuilder_.addAllMessages(other.children_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasName()) {
          return false;
        }
        if (!hasId()) {
          return false;
        }
        if (!hasValue()) {
          return false;
        }
        if (!hasType()) {
          return false;
        }
        for (int i = 0; i < getChildrenCount(); i++) {
          if (!getChildren(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.github.phantomv1989.diabrox.data.VisualObj.VisualNode parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.github.phantomv1989.diabrox.data.VisualObj.VisualNode) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <code>required string name = 1;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      private int id_ ;
      /**
       * <code>required int32 id = 2;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 id = 2;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required int32 id = 2;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000002;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 id = 2;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        id_ = 0;
        onChanged();
        return this;
      }

      private int value_ ;
      /**
       * <code>required int32 value = 3;</code>
       */
      public boolean hasValue() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 value = 3;</code>
       */
      public int getValue() {
        return value_;
      }
      /**
       * <code>required int32 value = 3;</code>
       */
      public Builder setValue(int value) {
        bitField0_ |= 0x00000004;
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 value = 3;</code>
       */
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000004);
        value_ = 0;
        onChanged();
        return this;
      }

      private int type_ ;
      /**
       * <code>required int32 type = 4;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int32 type = 4;</code>
       */
      public int getType() {
        return type_;
      }
      /**
       * <code>required int32 type = 4;</code>
       */
      public Builder setType(int value) {
        bitField0_ |= 0x00000008;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 type = 4;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000008);
        type_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<com.github.phantomv1989.diabrox.data.VisualObj.VisualNode> children_ =
        java.util.Collections.emptyList();
      private void ensureChildrenIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          children_ = new java.util.ArrayList<com.github.phantomv1989.diabrox.data.VisualObj.VisualNode>(children_);
          bitField0_ |= 0x00000010;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.github.phantomv1989.diabrox.data.VisualObj.VisualNode, com.github.phantomv1989.diabrox.data.VisualObj.VisualNode.Builder, com.github.phantomv1989.diabrox.data.VisualObj.VisualNodeOrBuilder> childrenBuilder_;

      /**
       * <code>repeated .com.github.phantomv1989.diabrox.data.VisualNode children = 5;</code>
       */
      public java.util.List<com.github.phantomv1989.diabrox.data.VisualObj.VisualNode> getChildrenList() {
        if (childrenBuilder_ == null) {
          return java.util.Collections.unmodifiableList(children_);
        } else {
          return childrenBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.github.phantomv1989.diabrox.data.VisualNode children = 5;</code>
       */
      public int getChildrenCount() {
        if (childrenBuilder_ == null) {
          return children_.size();
        } else {
          return childrenBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.github.phantomv1989.diabrox.data.VisualNode children = 5;</code>
       */
      public com.github.phantomv1989.diabrox.data.VisualObj.VisualNode getChildren(int index) {
        if (childrenBuilder_ == null) {
          return children_.get(index);
        } else {
          return childrenBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.github.phantomv1989.diabrox.data.VisualNode children = 5;</code>
       */
      public Builder setChildren(
          int index, com.github.phantomv1989.diabrox.data.VisualObj.VisualNode value) {
        if (childrenBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureChildrenIsMutable();
          children_.set(index, value);
          onChanged();
        } else {
          childrenBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.github.phantomv1989.diabrox.data.VisualNode children = 5;</code>
       */
      public Builder setChildren(
          int index, com.github.phantomv1989.diabrox.data.VisualObj.VisualNode.Builder builderForValue) {
        if (childrenBuilder_ == null) {
          ensureChildrenIsMutable();
          children_.set(index, builderForValue.build());
          onChanged();
        } else {
          childrenBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.github.phantomv1989.diabrox.data.VisualNode children = 5;</code>
       */
      public Builder addChildren(com.github.phantomv1989.diabrox.data.VisualObj.VisualNode value) {
        if (childrenBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureChildrenIsMutable();
          children_.add(value);
          onChanged();
        } else {
          childrenBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.github.phantomv1989.diabrox.data.VisualNode children = 5;</code>
       */
      public Builder addChildren(
          int index, com.github.phantomv1989.diabrox.data.VisualObj.VisualNode value) {
        if (childrenBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureChildrenIsMutable();
          children_.add(index, value);
          onChanged();
        } else {
          childrenBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.github.phantomv1989.diabrox.data.VisualNode children = 5;</code>
       */
      public Builder addChildren(
          com.github.phantomv1989.diabrox.data.VisualObj.VisualNode.Builder builderForValue) {
        if (childrenBuilder_ == null) {
          ensureChildrenIsMutable();
          children_.add(builderForValue.build());
          onChanged();
        } else {
          childrenBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.github.phantomv1989.diabrox.data.VisualNode children = 5;</code>
       */
      public Builder addChildren(
          int index, com.github.phantomv1989.diabrox.data.VisualObj.VisualNode.Builder builderForValue) {
        if (childrenBuilder_ == null) {
          ensureChildrenIsMutable();
          children_.add(index, builderForValue.build());
          onChanged();
        } else {
          childrenBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.github.phantomv1989.diabrox.data.VisualNode children = 5;</code>
       */
      public Builder addAllChildren(
          java.lang.Iterable<? extends com.github.phantomv1989.diabrox.data.VisualObj.VisualNode> values) {
        if (childrenBuilder_ == null) {
          ensureChildrenIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, children_);
          onChanged();
        } else {
          childrenBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.github.phantomv1989.diabrox.data.VisualNode children = 5;</code>
       */
      public Builder clearChildren() {
        if (childrenBuilder_ == null) {
          children_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
          onChanged();
        } else {
          childrenBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.github.phantomv1989.diabrox.data.VisualNode children = 5;</code>
       */
      public Builder removeChildren(int index) {
        if (childrenBuilder_ == null) {
          ensureChildrenIsMutable();
          children_.remove(index);
          onChanged();
        } else {
          childrenBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.github.phantomv1989.diabrox.data.VisualNode children = 5;</code>
       */
      public com.github.phantomv1989.diabrox.data.VisualObj.VisualNode.Builder getChildrenBuilder(
          int index) {
        return getChildrenFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.github.phantomv1989.diabrox.data.VisualNode children = 5;</code>
       */
      public com.github.phantomv1989.diabrox.data.VisualObj.VisualNodeOrBuilder getChildrenOrBuilder(
          int index) {
        if (childrenBuilder_ == null) {
          return children_.get(index);  } else {
          return childrenBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.github.phantomv1989.diabrox.data.VisualNode children = 5;</code>
       */
      public java.util.List<? extends com.github.phantomv1989.diabrox.data.VisualObj.VisualNodeOrBuilder> 
           getChildrenOrBuilderList() {
        if (childrenBuilder_ != null) {
          return childrenBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(children_);
        }
      }
      /**
       * <code>repeated .com.github.phantomv1989.diabrox.data.VisualNode children = 5;</code>
       */
      public com.github.phantomv1989.diabrox.data.VisualObj.VisualNode.Builder addChildrenBuilder() {
        return getChildrenFieldBuilder().addBuilder(
            com.github.phantomv1989.diabrox.data.VisualObj.VisualNode.getDefaultInstance());
      }
      /**
       * <code>repeated .com.github.phantomv1989.diabrox.data.VisualNode children = 5;</code>
       */
      public com.github.phantomv1989.diabrox.data.VisualObj.VisualNode.Builder addChildrenBuilder(
          int index) {
        return getChildrenFieldBuilder().addBuilder(
            index, com.github.phantomv1989.diabrox.data.VisualObj.VisualNode.getDefaultInstance());
      }
      /**
       * <code>repeated .com.github.phantomv1989.diabrox.data.VisualNode children = 5;</code>
       */
      public java.util.List<com.github.phantomv1989.diabrox.data.VisualObj.VisualNode.Builder> 
           getChildrenBuilderList() {
        return getChildrenFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.github.phantomv1989.diabrox.data.VisualObj.VisualNode, com.github.phantomv1989.diabrox.data.VisualObj.VisualNode.Builder, com.github.phantomv1989.diabrox.data.VisualObj.VisualNodeOrBuilder> 
          getChildrenFieldBuilder() {
        if (childrenBuilder_ == null) {
          childrenBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.github.phantomv1989.diabrox.data.VisualObj.VisualNode, com.github.phantomv1989.diabrox.data.VisualObj.VisualNode.Builder, com.github.phantomv1989.diabrox.data.VisualObj.VisualNodeOrBuilder>(
                  children_,
                  ((bitField0_ & 0x00000010) == 0x00000010),
                  getParentForChildren(),
                  isClean());
          children_ = null;
        }
        return childrenBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.github.phantomv1989.diabrox.data.VisualNode)
    }

    // @@protoc_insertion_point(class_scope:com.github.phantomv1989.diabrox.data.VisualNode)
    private static final com.github.phantomv1989.diabrox.data.VisualObj.VisualNode DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.github.phantomv1989.diabrox.data.VisualObj.VisualNode();
    }

    public static com.github.phantomv1989.diabrox.data.VisualObj.VisualNode getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<VisualNode>
        PARSER = new com.google.protobuf.AbstractParser<VisualNode>() {
      @java.lang.Override
      public VisualNode parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new VisualNode(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<VisualNode> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<VisualNode> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.github.phantomv1989.diabrox.data.VisualObj.VisualNode getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_github_phantomv1989_diabrox_data_VisualNode_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_github_phantomv1989_diabrox_data_VisualNode_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017VisualObj.proto\022$com.github.phantomv19" +
      "89.diabrox.data\"\207\001\n\nVisualNode\022\014\n\004name\030\001" +
      " \002(\t\022\n\n\002id\030\002 \002(\005\022\r\n\005value\030\003 \002(\005\022\014\n\004type\030" +
      "\004 \002(\005\022B\n\010children\030\005 \003(\01320.com.github.pha" +
      "ntomv1989.diabrox.data.VisualNodeB1\n$com" +
      ".github.phantomv1989.diabrox.dataB\tVisua" +
      "lObj"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_github_phantomv1989_diabrox_data_VisualNode_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_github_phantomv1989_diabrox_data_VisualNode_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_github_phantomv1989_diabrox_data_VisualNode_descriptor,
        new java.lang.String[] { "Name", "Id", "Value", "Type", "Children", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
